_BASE_: "image_joint_r50.yaml"
MODEL:
  WEIGHTS: "weights/R-50.pkl"
  RETRIEVAL: True
  USE_EARLY_FUSION: False
  USE_BIAS: False
  USE_BATCH_LOSS: True
  DDETRS:
    BATCH_LOSS_WEIGHT: 2.0

DATASETS:
  TRAIN: ("refcoco-mixed", )
  TEST: ("refcocog-umd-val", )
  # "refcoco-unc-testA", "refcoco-unc-testB", "refcocoplus-unc-val", "refcocoplus-unc-testA", "refcocoplus-unc-testB", "refcocog-google-val", "refcocog-umd-val", "refcocog-umd-test"
SOLVER:
  STEPS: (60000,)
  MAX_ITER: 80000 
  IMS_PER_BATCH: 64
  BASE_LR: 0.0002 # 2e-4

DATALOADER:
  DATASET_RATIO: [1]
  DATASET_BS: [8]
  USE_RFS: [False]
OUTPUT_DIR: outputs/retrieval_train_continue

TEST:
  EVAL_PERIOD: 2000

# python projects/CLARE/train_net.py --num-gpus 8 --config-file projects/CLARE/configs/retrieval_train_continue.yaml --resume

